version: "3.4"
services:
    nginx_example:
        container_name: nginx_example
        image: nginx_example:latest
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "443:443"
        restart: unless-stopped
